- name: ===================== FIND FOLDERS =====================
  find:
    paths: '{{Tools_path}}'
    patterns: '*'
    file_type: directory
  register: folder

- name: ===================== SHOW FOLDERS =====================
  #debug: msg="{{ file.file | sort(attribute='ctime') |  list }}"
  debug: msg="{{ folder.files | json_query('files."path"') }}"

- name: ===================== BASH ===================== 
  shell: echo {{ folder.files | json_query('uid')}}
