- name: ===================== FIND FOLDERS =====================
  find:
    paths: '{{Tools_path}}'
    patterns: '*'
    file_type: directory
  register: folder

- name: ===================== SHOW FOLDERS =====================
  #debug: msg="{{ file.file | sort(attribute='ctime') |  list }}"
  debug: msg="{{ folder.files|map('extract', ['path'])|list }}"

- name: ===================== BASH ===================== 
  shell: echo {{ folder.files }} | grep path


- name: ===================== DEBUG =====================
  debug: var=item
  with_items: "{{folder|json_query(server_name_cluster1_query)}}"  
  vars:
    server_name_cluster1_query: "files.path"
