- name: ===================== FIND FOLDERS =====================
  find:
    paths: '{{Tools_path}}'
    register: files

- name: ===================== SHOW FOLDERS =====================
  debug: msg="{{ files.files | sort(attribute='ctime') | map(attribute='path') | list }}"