- name: ===================== FIND FOLDERS =====================
  find:
    paths: '{{Tools_path}}'
  register: folders

- name: ===================== SHOW FOLDERS =====================
  debug: msg="{{ folders.folders | sort(attribute='ctime') |  list }}"