- name: ===================== FIND FOLDERS =====================
  find:
    paths: '{{Tools_path}}'
    patterns: *
#  register: folders

#- name: ===================== SHOW FOLDERS =====================
#  debug: msg="{{ folders.folders | sort(attribute='ctime') |  list }}"