- name: ===================== CHECK IF DIRECTORY '{{Tools_path}}' EXISTS =====================
  file:
    path: '{{Tools_path}}'
    state: directory
    mode: 0755
  become: yes
  
- name: ===================== DOWNLOAD TOOLS =====================
  unarchive:
    src: "{{item.path}}"
    dest: '{{Tools_path}}'    
    remote_src: yes
    keep_newer: yes  
  with_items:  "{{ ToolsList }}"
  become: yes
