- name: ===================== CHECK IF DIRECTORY '{{Tools_path}}' EXISTS =====================
  file:
    path: '{{Tools_path}}'
    state: directory
    mode: 0755
  become: yes

- name: ===================== DOWNLOAD TOOLS TO /tmp =====================
  get_url:
    url: "{{item.path}}"
    dest: "/tmp/{{item.name}}"
    url_username: __myUser__
    url_password: __myPassword__
    mode: 0440
  with_items:  "{{ ToolsList }}"


- name: ===================== GET TOOLS LIST =====================
  find:
    paths: '{{Tools_path}}'
    file_type: directory
  register: folder_list

#- name: = == LOOP== =
#  debug: var="{{ folder_list.files }}"
#  with_items:  "{{ folder_list.files }}"

- name: ===================== ADD VARIABLE IN buildAgent.property =====================
  buildAgentProperties:
    package: "{{item.path}}"
    property_file: "{{ property_file }}"
  with_items:  "{{ folder_list.files }}"
  #register: result
  no_log: True
  become: yes


#- name: ===================== UNARCHIVE BUILD TOOLS FROM /tmp to '{{Tools_path}}'  =====================
#  unarchive:
#    src: "/tmp/{{item.name}}"
#    dest: '{{Tools_path}}'
#    remote_src: yes
#  with_items:  "{{ ToolsList }}"
#  become: yes


#- name: ===================== DOWNLOAD AND UNARCHIVE TOOLS =====================
#  unarchive:
#    src: "{{item.path}}"
#    dest: '{{Tools_path}}'
#    remote_src: yes
#    keep_newer: yes
#  with_items:  "{{ ToolsList }}"
#  become: yes
