- name: ===================== CHECK IF DIRECTORY '{{Tools_path}}' EXISTS =====================
  file:
    path: '{{Tools_path}}'
    state: directory
    mode: 0755
  become: yes

- name: ===================== DOWNLOAD TOOLS TO /tmp =====================
  get_url:
    url: "{{item.path}}"
    dest: "/tmp/{{item.name}}"
    url_username: __myUser__
    url_password: __myPassword__
    mode: 0440
  with_items:  "{{ ToolsList }}"


- name: ++++ GET DIRECTORIES ++++
  find:
    paths: '{{Tools_path}}'
    file_type: directory
  register: folder_list

#- name: = == OUT == =
#  debug: var=folder_list.files[1].path

- name: = == LOOP== =
  debug: var="{{ folder_list.files.path }}"
  with_items:  "{{ folder_list.files }}"

- name: ===================== ADD VARIABLE IN buildAgent.property =====================
  buildAgentProperties:
    package: "{{item}}"
    property_file: "{{ property_file }}"
  with_dict:  "{{ folder_list.files }}"
  register: result
  become: yes

- name: = OUT =
  debug: var=result

#- name: ===================== UNARCHIVE BUILD TOOLS FROM /tmp to '{{Tools_path}}'  =====================
#  unarchive:
#    src: "/tmp/{{item.name}}"
#    dest: '{{Tools_path}}'
#    remote_src: yes
#  with_items:  "{{ ToolsList }}"
#  become: yes

#- name: ===================== XXX =====================
#  shell: echo {{item.name}} >> {{Tools_path}}/XXXX
#  #with_items:  "{{ ToolsList }}"
#  with_items:  "{{ ToolsList }}"
#  become: yes

#- name: ===================== Python =====================
#  shell: pwd >> {{Tools_path}}/XXXX
#  #with_items:  "{{ ToolsList }}"
#  #with_items:  "{{ ToolsList }}"
#  become: yes

#- name: ===================== Python2 =====================
#  shell: ls; /usr/bin/python27 script.py
#  #with_items:  "{{ ToolsList }}"
#  #with_items:  "{{ ToolsList }}"
#  become: yes

#- name: ===================== Check files  =====================
#  shell: echo "SW  {{ item.name }}"
#  with_items:  "{{ ToolsList }}"




#- name: ===================== DOWNLOAD AND UNARCHIVE TOOLS =====================
#  unarchive:
#    src: "{{item.path}}"
#    dest: '{{Tools_path}}'
#    remote_src: yes
#    keep_newer: yes
#  with_items:  "{{ ToolsList }}"
#  become: yes
