#- name: ===================== Install libselinux-python =====================
#  yum:
#    name: "{{item.name}}"
#    state: latest
#  with_items:  "{{ ToolsList }}"
#  become: yes
  
- name: ===================== DOWNLOAD TOOLS =====================
  unarchive:
    src: "{{item.path}}"
    dest: '{{Tools_path}}'
    with_items:  "{{ ToolsList }}"
    remote_src: yes
    keep_newer: yes    
  become: yes
