- name: ===================== CHECK IF DIRECTORY '{{Tools_path}}' EXISTS =====================
  file:
    path: '{{Tools_path}}'
    state: directory
    mode: 0755
  become: yes
  
- name: ===================== DOWNLOAD TOOLS =====================
  get_url:
    url: "{{item.path}}"
    dest: "/tmp/{{item.name}}"
    url_username: __myUser__
    url_password: __myPassword__
    mode: 0440
  with_items:  "{{ ToolsList }}"

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "/tmp/{{item.name}}"
    dest: '{{Tools_path}}'
    remote_src: yes
  with_items:  "{{ ToolsList }}"
  become: yes
  
#- name: ===================== DOWNLOAD AND UNARCHIVE TOOLS =====================
#  unarchive:
#    src: "{{item.path}}"
#    dest: '{{Tools_path}}'    
#    remote_src: yes
#    keep_newer: yes  
#  with_items:  "{{ ToolsList }}"
#  become: yes
